[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"
  hostname = "damoa.io"

[[outputs.influxdb]]
    urls = ["https://prometheus-us-central1.grafana.net/api/v1/push/influx"]
    skip_database_creation = true
    exclude_retention_policy_tag = true
    timeout = "30s"
    username = "686665"
    password = "my-grafana-secret"

[[inputs.mqtt_consumer]]
  servers   = ["tcp://damoa.io:1883"]
  topics    = ["ewha/distance/#"]
  data_format = "json_v2"
  topic_tag = "mqtt_topic"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "ewha"
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "@this"
      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "distance"
        type = "float"

# ek/data/sensor - 122T0
[[inputs.mqtt_consumer]]
  servers   = ["tcp://damoa.io:1883"]
  topics    = ["ek/sensor/122"]
  data_format = "json_v2"
  topic_tag = "mqtt_topic"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "ek"
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "@this"

      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "122T0"
        type = "float"
        optional = true

# ek/valvegod/60000 - 60000T0~T9
[[inputs.mqtt_consumer]]
  servers   = ["tcp://damoa.io:1883"]
  topics    = ["ek/valvegod/60000"]
  data_format = "json_v2"
  topic_tag = "mqtt_topic"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "ek"
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "@this"

      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "60000T0"
        type = "float"
        optional = true

      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "60000T1"
        type = "float"
        optional = true

      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "60000T2"
        type = "float"
        optional = true

      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "60000T3"
        type = "float"
        optional = true

      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "60000T4"
        type = "float"
        optional = true

      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "60000T5"
        type = "float"
        optional = true

      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "60000T6"
        type = "float"
        optional = true

      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "60000T7"
        type = "float"
        optional = true

      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "60000T9"
        type = "float"
        optional = true
