[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"
  hostname = "damoa.io"

[[outputs.influxdb]]
    urls = ["https://prometheus-us-central1.grafana.net/api/v1/push/influx"]
    skip_database_creation = true
    exclude_retention_policy_tag = true
    timeout = "30s"
    username = "686665"
    password = "your-own-grafana-api-key"

# ewha/distance/0317137263 
[[inputs.mqtt_consumer]]
  servers   = ["tcp://damoa.io:1883"]
  topics    = ["ewha/distance/0317137263"]
  data_format = "json_v2"
  topic_tag = "mqtt_topic"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "ewha"
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "@this"
      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "distance"
        type = "float"

# ewha/0317137263 
[[inputs.mqtt_consumer]]
  servers   = ["tcp://damoa.io:1883"]
  topics    = ["ewha/0317137263"]
  data_format = "json_v2"
  topic_tag = "mqtt_topic"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "ewha"
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "@this"

      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "온도"
        type = "float"
        optional = true

      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "습도"
        type = "float"
        optional = true
